import type { Product } from "@/types/product";

export const MOCK_PRODUCTS: Product[] = [
  {
    id: "sat-001",
    slug: "satrapa-carioca-250",
    nombre: "Sátrapa Carioca",
    categoria: "cafe x 250gr",
    precio: 8500,
    stock: 12,
    descripcionCorta: "Brasil, dulce y chocolatoso. El que te despierta sin pelearte.",
    descripcionLarga:
      "Un Brasil de la región de Cerrado Mineiro, procesado natural. Notas redondas a chocolate con leche, caramelo y un final suave a nuez. Ideal para espresso, moka o filtrado largo. El café que abraza.",
    origen: "Cerrado Mineiro, Brasil",
    notasCata: ["chocolate", "caramelo", "nuez"],
    imagenPrincipal: "satrapa/products/brasil-carioca",
    imagenesExtra: [],
    activo: true,
  },
  {
    id: "sat-002",
    slug: "satrapa-descarada-500",
    nombre: "Sátrapa Descarada",
    categoria: "cafe x 500gr",
    precio: 15200,
    stock: 24,
    descripcionCorta: "Blend intenso para los que no piden permiso.",
    descripcionLarga:
      "Nuestro blend insignia: 70% Brasil natural + 30% Colombia lavado. Cuerpo firme, crema densa y un dulzor que no se apura. Para mañanas rebeldes y sobremesas que se estiran.",
    notasCata: ["cacao", "panela", "frutos rojos"],
    imagenPrincipal: "satrapa/products/descarada",
    imagenesExtra: [],
    activo: true,
  },
  {
    id: "sat-003",
    slug: "satrapa-al-sol-250",
    nombre: "Sátrapa al Sol",
    categoria: "cafe x 250gr",
    precio: 9600,
    stock: 4,
    descripcionCorta: "Etiopía lavado. Floral, cítrico, imposible de apurar.",
    descripcionLarga:
      "Yirgacheffe de altura, proceso lavado. Aromas a jazmín, bergamota y durazno blanco. Perfecto en V60 o Chemex. El café para esa pausa que nadie mira pero todos necesitamos.",
    origen: "Yirgacheffe, Etiopía",
    notasCata: ["jazmín", "bergamota", "durazno"],
    imagenPrincipal: "satrapa/products/al-sol",
    imagenesExtra: [],
    activo: true,
  },
  {
    id: "sat-004",
    slug: "satrapa-carioca-1kg",
    nombre: "Sátrapa Carioca",
    categoria: "cafe x 1kg",
    precio: 30000,
    stock: 6,
    descripcionCorta: "El Carioca formato cafetería. Para los que toman en serio su mañana.",
    descripcionLarga:
      "Mismo Brasil Cerrado Mineiro que amás, en formato kilo. Para la cafetería, la oficina o el sátrapa confeso que no quiere quedarse sin.",
    origen: "Cerrado Mineiro, Brasil",
    notasCata: ["chocolate", "caramelo", "nuez"],
    imagenPrincipal: "satrapa/products/brasil-carioca",
    imagenesExtra: [],
    activo: true,
  },
  {
    id: "sat-005",
    slug: "moka-bialetti-3",
    nombre: "Cafetera Moka 3 pocillos",
    categoria: "cafeteras",
    precio: 42000,
    stock: 5,
    descripcionCorta: "La clásica italiana para rituales lentos.",
    descripcionLarga:
      "Moka de aluminio estilo Bialetti, 3 tazas. Para preparar un café intenso, cremoso y a fuego lento. Un cacharro que dura una vida.",
    notasCata: [],
    imagenPrincipal: "satrapa/products/moka",
    imagenesExtra: [],
    activo: true,
  },
  {
    id: "sat-006",
    slug: "filtros-v60",
    nombre: "Filtros V60 (40u.)",
    categoria: "accesorios",
    precio: 3800,
    stock: 40,
    descripcionCorta: "Papelitos para esa pausa bien ritualera.",
    descripcionLarga:
      "Pack de 40 filtros de papel para V60 tamaño 02. Sabor limpio, cuerpo fino, cero quilombo.",
    notasCata: [],
    imagenPrincipal: "satrapa/products/filtros-v60",
    imagenesExtra: [],
    activo: true,
  },
];
